In [17]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('COVID-19 Survey Student Responses.csv')

In [3]:
df.head(10)

,ID,Region of residence,Age of Subject,Time spent on Online Class,Rating of Online Class experience,Medium for online class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Prefered social media platform,Time spent on TV,Number of meals per day,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
0,R1,Delhi-NCR,21,2.0,Good,Laptop/Desktop,4.0,0.0,7.0,3.0,Linkedin,1,4,Increased,NO,Cooking,YES,YES,School/college
1,R2,Delhi-NCR,21,0.0,Excellent,Smartphone,0.0,2.0,10.0,3.0,Youtube,0,3,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely
2,R3,Delhi-NCR,20,7.0,Very poor,Laptop/Desktop,3.0,0.0,6.0,2.0,Linkedin,0,3,Remain Constant,NO,Listening to music,NO,YES,Travelling
3,R4,Delhi-NCR,20,3.0,Very poor,Smartphone,2.0,1.0,6.0,5.0,Instagram,0,3,Decreased,NO,Watching web series,NO,NO,"Friends , relatives"
4,R5,Delhi-NCR,21,3.0,Good,Laptop/Desktop,3.0,1.0,8.0,3.0,Instagram,1,4,Remain Constant,NO,Social Media,NO,NO,Travelling
5,R6,Delhi-NCR,21,0.0,Very poor,Smartphone,6.0,0.0,5.0,1.0,Youtube,0,1,Decreased,YES,Coding and studying for exams,NO,YES,School/college
6,R7,Delhi-NCR,19,2.0,Very poor,Smartphone,2.0,1.0,5.0,4.0,Instagram,0,3,Increased,NO,Watching web series,NO,YES,"Friends , relatives"
7,R8,Outside Delhi-NCR,19,2.0,Very poor,Tablet,1.0,1.0,10.0,5.0,Instagram,0,3,Increased,YES,Scrolling through social media,NO,YES,Eating outside
8,R9,Delhi-NCR,21,3.0,Very poor,Laptop/Desktop,4.0,1.0,8.0,2.0,Whatsapp,1,3,Increased,NO,Online surfing,NO,NO,"Friends , relatives"
9,R10,Outside Delhi-NCR,20,0.0,Very poor,Laptop/Desktop,1.0,0.5,8.0,5.0,Instagram,3,3,Decreased,YES,live stream watching,NO,NO,School/college

# Drop the column ID , region of residence which is not used for further calculation.

In [4]:
df.drop(["ID","Region of residence"],axis=1,inplace=True)
df

,Age of Subject,Time spent on Online Class,Rating of Online Class experience,Medium for online class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Prefered social media platform,Time spent on TV,Number of meals per day,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
0,21,2.0,Good,Laptop/Desktop,4.0,0.0,7.0,3.0,Linkedin,1,4,Increased,NO,Cooking,YES,YES,School/college
1,21,0.0,Excellent,Smartphone,0.0,2.0,10.0,3.0,Youtube,0,3,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely
2,20,7.0,Very poor,Laptop/Desktop,3.0,0.0,6.0,2.0,Linkedin,0,3,Remain Constant,NO,Listening to music,NO,YES,Travelling
3,20,3.0,Very poor,Smartphone,2.0,1.0,6.0,5.0,Instagram,0,3,Decreased,NO,Watching web series,NO,NO,"Friends , relatives"
4,21,3.0,Good,Laptop/Desktop,3.0,1.0,8.0,3.0,Instagram,1,4,Remain Constant,NO,Social Media,NO,NO,Travelling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,12,3.0,Good,Smartphone,4.0,1.0,8.0,1.0,Instagram,2,3,Decreased,NO,Dancing,YES,YES,Travelling
1178,14,6.0,Average,Smartphone,4.0,1.0,9.0,1.0,Whatsapp,1,4,Remain Constant,NO,Listening to music,YES,YES,"Friends , relatives"
1179,13,4.0,Average,Smartphone,0.0,0.5,8.0,3.0,Youtube,2,4,Decreased,NO,Online gaming,NO,YES,School/college
1180,14,5.0,Excellent,Laptop/Desktop,3.5,1.0,8.0,0.5,Youtube,1,4,Remain Constant,NO,Reading books,YES,YES,School/college
1181,13,5.0,Good,Tablet,2.0,0.5,7.0,1.0,Whatsapp,1,3,Remain Constant,NO,Talking,YES,YES,School/college

# Dataset taken is checked for any NAN and NULL values

In [5]:
df.isnull().sum()

Age of Subject                                                                         0
Time spent on Online Class                                                             0
Rating of Online Class experience                                                     24
Medium for online class                                                               51
Time spent on self study                                                               0
Time spent on fitness                                                                  0
Time spent on sleep                                                                    0
Time spent on social media                                                             0
Prefered social media platform                                                        17
Time spent on TV                                                                       0
Number of meals per day                                                                0
Change in your weight                                                                  0
Health issue during lockdown                                                           0
Stress busters                                                                         0
Time utilized                                                                          0
Do you find yourself more connected with your family, close friends , relatives  ?     0
What you miss the most                                                                 0
dtype: int64

In [6]:
df.shape

(1182, 17)

# Finding the datatype of each column

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 17 columns):
 #   Column                                                                              Non-Null Count  Dtype
---  ------                                                                              --------------  -----
 0   Age of Subject                                                                      1182 non-null   int64
 1   Time spent on Online Class                                                          1182 non-null   float64
 2   Rating of Online Class experience                                                   1158 non-null   object
 3   Medium for online class                                                             1131 non-null   object
 4   Time spent on self study                                                            1182 non-null   float64
 5   Time spent on fitness                                                               1182 non-null   float64
 6   Time spent on sleep                                                                 1182 non-null   float64
 7   Time spent on social media                                                          1182 non-null   float64
 8   Prefered social media platform                                                      1165 non-null   object
 9   Time spent on TV                                                                    1182 non-null   object
 10  Number of meals per day                                                             1182 non-null   int64
 11  Change in your weight                                                               1182 non-null   object
 12  Health issue during lockdown                                                        1182 non-null   object
 13  Stress busters                                                                      1182 non-null   object
 14  Time utilized                                                                       1182 non-null   object
 15  Do you find yourself more connected with your family, close friends , relatives  ?  1182 non-null   object
 16  What you miss the most                                                              1182 non-null   object
dtypes: float64(5), int64(2), object(10)
memory usage: 157.1+ KB

# Rating of Online Class experience, Medium for online class ,  Prefered social media platform are the columns in object datatype having null values so those columns are replaced as Not Interested

In [8]:
df.fillna('Not Interested',inplace=True)

In [9]:
df.isnull().sum()

Age of Subject                                                                        0
Time spent on Online Class                                                            0
Rating of Online Class experience                                                     0
Medium for online class                                                               0
Time spent on self study                                                              0
Time spent on fitness                                                                 0
Time spent on sleep                                                                   0
Time spent on social media                                                            0
Prefered social media platform                                                        0
Time spent on TV                                                                      0
Number of meals per day                                                               0
Change in your weight                                                                 0
Health issue during lockdown                                                          0
Stress busters                                                                        0
Time utilized                                                                         0
Do you find yourself more connected with your family, close friends , relatives  ?    0
What you miss the most                                                                0
dtype: int64

# Health issue during lockdown is the output column (dependent variable)

In [10]:
df.describe()

,Age of Subject,Time spent on Online Class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Number of meals per day
count,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000,1182.000000
mean,20.165821,3.208841,2.911591,0.765821,7.871235,2.365694,2.917936
std,5.516467,2.101756,2.140590,0.724451,1.615762,1.767336,0.828698
min,7.000000,0.000000,0.000000,0.000000,4.000000,0.000000,1.000000
25%,17.000000,2.000000,2.000000,0.000000,7.000000,1.000000,2.000000
50%,20.000000,3.000000,2.000000,1.000000,8.000000,2.000000,3.000000
75%,21.000000,5.000000,4.000000,1.000000,9.000000,3.000000,3.000000
max,59.000000,10.000000,18.000000,5.000000,15.000000,10.000000,8.000000

# Working to find Outliers

# 1. Splitting of quan and qual columns

In [12]:
quan=[]
qual=[]
for colName in df.columns:
    if (df[colName].dtypes)=='object':
        qual.append(colName)
    else:
        quan.append(colName)

In [13]:
quan

['Age of Subject',
 'Time spent on Online Class',
 'Time spent on self study',
 'Time spent on fitness',
 'Time spent on sleep',
 'Time spent on social media',
 'Number of meals per day']

In [14]:
qual

['Rating of Online Class experience',
 'Medium for online class',
 'Prefered social media platform',
 'Time spent on TV',
 'Change in your weight',
 'Health issue during lockdown',
 'Stress busters',
 'Time utilized',
 'Do you find yourself more connected with your family, close friends , relatives  ?',
 'What you miss the most']

# 2. Understanding the dataset deeper using Central Tendency, IQR ,Min & Max value

In [19]:
descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25","Q2:50","Q3:75","99th","Q4:100",
                               "IQR","1.5IQR","LesserRange","GreaterRange","MinValue","MaxValue"],columns=quan)
for colName in quan:
    descriptive[colName]["mean"]=df[colName].mean()
    descriptive[colName]["median"]=df[colName].median()
    descriptive[colName]["mode"]=df[colName].mode()[0]
    descriptive[colName]["Q1:25"]=df.describe()[colName]["25%"]
    descriptive[colName]["Q2:50"]=df.describe()[colName]["50%"]
    descriptive[colName]["Q3:75"]=df.describe()[colName]["75%"]
    descriptive[colName]["99th"]=np.percentile(df[colName],99)
    descriptive[colName]["Q4:100"]=df.describe()[colName]["max"]
    descriptive[colName]["IQR"]=descriptive[colName]["Q3:75"]- descriptive[colName]["Q1:25"]
    descriptive[colName]["1.5IQR"]=1.5 * descriptive[colName]["IQR"]
    descriptive[colName]["LesserRange"]= descriptive[colName]["Q1:25"] - descriptive[colName]["1.5IQR"]
    descriptive[colName]["GreaterRange"]= descriptive[colName]["Q3:75"] + descriptive[colName]["1.5IQR"]
    descriptive[colName]["MinValue"]=df[colName].min()
    descriptive[colName]["MaxValue"]=df[colName].max()

In [20]:
descriptive

,Age of Subject,Time spent on Online Class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Number of meals per day
mean,20.165821,3.208841,2.911591,0.765821,7.871235,2.365694,2.917936
median,20.0,3.0,2.0,1.0,8.0,2.0,3.0
mode,20,4.0,2.0,1.0,8.0,1.0,3
Q1:25,17.0,2.0,2.0,0.0,7.0,1.0,2.0
Q2:50,20.0,3.0,2.0,1.0,8.0,2.0,3.0
Q3:75,21.0,5.0,4.0,1.0,9.0,3.0,3.0
99th,40.0,8.0,10.0,3.0,12.0,10.0,5.0
Q4:100,59.0,10.0,18.0,5.0,15.0,10.0,8.0
IQR,4.0,3.0,2.0,1.0,2.0,2.0,1.0
1.5IQR,6.0,4.5,3.0,1.5,3.0,3.0,1.5
LesserRange,11.0,-2.5,-1.0,-1.5,4.0,-2.0,0.5
GreaterRange,27.0,9.5,7.0,2.5,12.0,6.0,4.5
MinValue,7,0.0,0.0,0.0,4.0,0.0,1
MaxValue,59,10.0,18.0,5.0,15.0,10.0,8

# 3. Checking for Outlier

In [21]:
lesserOutlier=[]
greaterOutlier=[]
for colName in quan:
    if(descriptive[colName]["LesserRange"] > descriptive[colName]["MinValue"]):
        lesserOutlier.append(colName)
    if(descriptive[colName]["GreaterRange"] < descriptive[colName]["MaxValue"]):
        greaterOutlier.append(colName)

In [22]:
lesserOutlier

['Age of Subject']

In [23]:
greaterOutlier

['Age of Subject',
 'Time spent on Online Class',
 'Time spent on self study',
 'Time spent on fitness',
 'Time spent on sleep',
 'Time spent on social media',
 'Number of meals per day']

# 4. Replacing Ouliers

In [25]:
for colName in lesserOutlier:
    df[colName][df[colName]<descriptive[colName]["LesserRange"]]=descriptive[colName]["LesserRange"]
for colName in greaterOutlier:
    df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]

C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]<descriptive[colName]["LesserRange"]]=descriptive[colName]["LesserRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]
C:\Users\ELCOT\AppData\Local\Temp\ipykernel_1044\4182253629.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '4.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df[colName][df[colName]>descriptive[colName]["GreaterRange"]]=descriptive[colName]["GreaterRange"]

In [26]:
descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25","Q2:50","Q3:75","99th","Q4:100",
                               "IQR","1.5IQR","LesserRange","GreaterRange","MinValue","MaxValue"],columns=quan)
for colName in quan:
    descriptive[colName]["mean"]=df[colName].mean()
    descriptive[colName]["median"]=df[colName].median()
    descriptive[colName]["mode"]=df[colName].mode()[0]
    descriptive[colName]["Q1:25"]=df.describe()[colName]["25%"]
    descriptive[colName]["Q2:50"]=df.describe()[colName]["50%"]
    descriptive[colName]["Q3:75"]=df.describe()[colName]["75%"]
    descriptive[colName]["99th"]=np.percentile(df[colName],99)
    descriptive[colName]["Q4:100"]=df.describe()[colName]["max"]
    descriptive[colName]["IQR"]=descriptive[colName]["Q3:75"]- descriptive[colName]["Q1:25"]
    descriptive[colName]["1.5IQR"]=1.5 * descriptive[colName]["IQR"]
    descriptive[colName]["LesserRange"]= descriptive[colName]["Q1:25"] - descriptive[colName]["1.5IQR"]
    descriptive[colName]["GreaterRange"]= descriptive[colName]["Q3:75"] + descriptive[colName]["1.5IQR"]
    descriptive[colName]["MinValue"]=df[colName].min()
    descriptive[colName]["MaxValue"]=df[colName].max()

In [27]:
descriptive

,Age of Subject,Time spent on Online Class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Number of meals per day
mean,19.571066,3.207149,2.803299,0.751861,7.861083,2.286168,2.900592
median,20.0,3.0,2.0,1.0,8.0,2.0,3.0
mode,20,4.0,2.0,1.0,8.0,1.0,3.0
Q1:25,17.0,2.0,2.0,0.0,7.0,1.0,2.0
Q2:50,20.0,3.0,2.0,1.0,8.0,2.0,3.0
Q3:75,21.0,5.0,4.0,1.0,9.0,3.0,3.0
99th,27.0,8.0,7.0,2.5,12.0,6.0,4.5
Q4:100,27.0,9.5,7.0,2.5,12.0,6.0,4.5
IQR,4.0,3.0,2.0,1.0,2.0,2.0,1.0
1.5IQR,6.0,4.5,3.0,1.5,3.0,3.0,1.5
LesserRange,11.0,-2.5,-1.0,-1.5,4.0,-2.0,0.5
GreaterRange,27.0,9.5,7.0,2.5,12.0,6.0,4.5
MinValue,11,0.0,0.0,0.0,4.0,0.0,1.0
MaxValue,27,9.5,7.0,2.5,12.0,6.0,4.5

In [28]:
lesserOutlier=[]
greaterOutlier=[]
for colName in quan:
    if(descriptive[colName]["LesserRange"] > descriptive[colName]["MinValue"]):
        lesserOutlier.append(colName)
    if(descriptive[colName]["GreaterRange"] < descriptive[colName]["MaxValue"]):
        greaterOutlier.append(colName)

In [29]:
lesserOutlier

[]

In [30]:
greaterOutlier

[]

In [31]:
df

,Age of Subject,Time spent on Online Class,Rating of Online Class experience,Medium for online class,Time spent on self study,Time spent on fitness,Time spent on sleep,Time spent on social media,Prefered social media platform,Time spent on TV,Number of meals per day,Change in your weight,Health issue during lockdown,Stress busters,Time utilized,"Do you find yourself more connected with your family, close friends , relatives ?",What you miss the most
0,21,2.0,Good,Laptop/Desktop,4.0,0.0,7.0,3.0,Linkedin,1,4.0,Increased,NO,Cooking,YES,YES,School/college
1,21,0.0,Excellent,Smartphone,0.0,2.0,10.0,3.0,Youtube,0,3.0,Decreased,NO,Scrolling through social media,YES,NO,Roaming around freely
2,20,7.0,Very poor,Laptop/Desktop,3.0,0.0,6.0,2.0,Linkedin,0,3.0,Remain Constant,NO,Listening to music,NO,YES,Travelling
3,20,3.0,Very poor,Smartphone,2.0,1.0,6.0,5.0,Instagram,0,3.0,Decreased,NO,Watching web series,NO,NO,"Friends , relatives"
4,21,3.0,Good,Laptop/Desktop,3.0,1.0,8.0,3.0,Instagram,1,4.0,Remain Constant,NO,Social Media,NO,NO,Travelling
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,12,3.0,Good,Smartphone,4.0,1.0,8.0,1.0,Instagram,2,3.0,Decreased,NO,Dancing,YES,YES,Travelling
1178,14,6.0,Average,Smartphone,4.0,1.0,9.0,1.0,Whatsapp,1,4.0,Remain Constant,NO,Listening to music,YES,YES,"Friends , relatives"
1179,13,4.0,Average,Smartphone,0.0,0.5,8.0,3.0,Youtube,2,4.0,Decreased,NO,Online gaming,NO,YES,School/college
1180,14,5.0,Excellent,Laptop/Desktop,3.5,1.0,8.0,0.5,Youtube,1,4.0,Remain Constant,NO,Reading books,YES,YES,School/college
1181,13,5.0,Good,Tablet,2.0,0.5,7.0,1.0,Whatsapp,1,3.0,Remain Constant,NO,Talking,YES,YES,School/college

In [32]:
df['Age of Subject'].min()

11

In [33]:
df['Time spent on Online Class'].max()

9.5

In [34]:
df.to_csv("preCovidStudentSurvey.csv",index=0)

In [35]:
df['Age of Subject'].value_counts()

Age of Subject
20    211
21    188
19    138
22     93
27     93
16     67
18     66
17     58
14     48
13     48
23     44
15     37
12     29
24     23
11     15
25     12
26     12
Name: count, dtype: int64

In [36]:
df['Rating of Online Class experience'].value_counts()

Rating of Online Class experience
Very poor         413
Average           387
Good              230
Excellent          98
Poor               30
Not Interested     24
Name: count, dtype: int64

In [37]:
df['Time spent on Online Class'].value_counts()

Time spent on Online Class
4.00    222
2.00    201
3.00    177
5.00    142
0.00    132
1.00    114
6.00     91
7.00     31
8.00     31
0.50     10
0.75      7
1.50      5
9.00      5
9.50      4
5.50      3
2.50      2
0.70      1
3.50      1
0.80      1
0.10      1
7.50      1
Name: count, dtype: int64

In [38]:
df['Medium for online class'].value_counts()

Medium for online class
Laptop/Desktop                  545
Smartphone                      539
Not Interested                   51
Tablet                           37
Any Gadget                        5
Smartphone or Laptop/Desktop      5
Name: count, dtype: int64

In [39]:
df['Time spent on self study'].value_counts()

Time spent on self study
2.0    346
3.0    202
1.0    180
4.0    151
0.0     76
5.0     76
7.0     68
6.0     53
0.5      9
1.5      7
2.5      7
3.5      3
2.3      1
1.2      1
6.5      1
4.5      1
Name: count, dtype: int64

In [40]:
df['Time spent on fitness'].value_counts()

Time spent on fitness
1.00    550
0.00    419
2.00    119
0.50     53
2.50     28
0.25      6
0.30      5
0.60      2
Name: count, dtype: int64

In [41]:
df['Time spent on sleep'].value_counts()

Time spent on sleep
8.0     390
7.0     256
6.0     171
9.0     132
10.0     96
12.0     50
5.0      46
11.0     25
4.0       5
7.5       4
6.5       3
7.8       1
6.7       1
8.5       1
8.3       1
Name: count, dtype: int64

In [42]:
df['Time spent on social media'].value_counts()

Time spent on social media
1.00    343
2.00    335
3.00    169
4.00    112
6.00     66
5.00     58
0.00     36
0.50     34
1.50     15
0.30      4
0.10      2
0.40      2
0.15      1
3.50      1
0.60      1
0.75      1
1.30      1
0.25      1
Name: count, dtype: int64

In [43]:
df['Time spent on TV'].value_counts()

Time spent on TV
0        441
1        306
2        207
0.5       78
3         50
4         24
1.5       14
0.3       12
5         10
6          9
N          7
0.1        4
No tv      3
4.5        2
7          2
8          2
           2
2.5        2
0.25       1
n          1
0.6        1
15         1
0.75       1
3.5        1
0.4        1
Name: count, dtype: int64

In [44]:
df['Time spent on TV'].replace(to_replace=['n','N','No tv',' '] , value='0', 
                                      inplace=True)

In [45]:
df['Time spent on TV'].value_counts()

Time spent on TV
0       454
1       306
2       207
0.5      78
3        50
4        24
1.5      14
0.3      12
5        10
6         9
0.1       4
4.5       2
7         2
8         2
2.5       2
0.25      1
0.6       1
15        1
0.75      1
3.5       1
0.4       1
Name: count, dtype: int64

In [47]:
df['Prefered social media platform'].value_counts()

Prefered social media platform
Instagram         352
Whatsapp          336
Youtube           314
Linkedin           61
Facebook           52
Twitter            28
Not Interested     17
Snapchat            8
Reddit              5
Telegram            3
Omegle              1
Elyment             1
None                1
Quora               1
Talklife            1
WhatsApp            1
Name: count, dtype: int64

In [48]:
df['Number of meals per day'].value_counts()

Number of meals per day
3.0    610
2.0    287
4.0    229
1.0     41
4.5     15
Name: count, dtype: int64

In [49]:
df['Change in your weight'].value_counts()

Change in your weight
Remain Constant    535
Increased          438
Decreased          209
Name: count, dtype: int64

In [50]:
df['Health issue during lockdown'].value_counts()

Health issue during lockdown
NO     1021
YES     161
Name: count, dtype: int64

In [51]:
df['Stress busters'].value_counts()

Stress busters
Listening to music                276
Online gaming                     175
Watching web series               102
Reading books                      77
Scrolling through social media     74
                                 ...
I run                               1
Running                             1
Football                            1
singing                             1
Watching YouTube                    1
Name: count, Length: 86, dtype: int64

In [52]:
df['Time utilized'].value_counts()

Time utilized
NO     608
YES    574
Name: count, dtype: int64

In [54]:
df['Do you find yourself more connected with your family, close friends , relatives  ?'].value_counts()

Do you find yourself more connected with your family, close friends , relatives  ?
YES    831
NO     351
Name: count, dtype: int64

In [55]:
df['What you miss the most'].value_counts()

What you miss the most
School/college                                                                                                                                                                                                              379
Friends , relatives                                                                                                                                                                                                         223
Travelling                                                                                                                                                                                                                  183
Roaming around freely                                                                                                                                                                                                       149
Eating outside                                                                                                                                                                                                              104
Colleagues                                                                                                                                                                                                                   67
Nothing                                                                                                                                                                                                                      11
ALL                                                                                                                                                                                                                           9
All                                                                                                                                                                                                                           9
Gym                                                                                                                                                                                                                           4
nothing                                                                                                                                                                                                                       2
NOTHING                                                                                                                                                                                                                       2
Only friends                                                                                                                                                                                                                  2
Playing                                                                                                                                                                                                                       1
Being social                                                                                                                                                                                                                  1
all                                                                                                                                                                                                                           1
Previous mistakes                                                                                                                                                                                                             1
.                                                                                                                                                                                                                             1
To stay alone.                                                                                                                                                                                                                1
I have missed nothing                                                                                                                                                                                                         1
Travelling & Friends                                                                                                                                                                                                          1
The idea of being around fun loving people but this time has certainly made us all to reconnect (and fill the gap if any) with our families and relatives so it is fun but certainly we do miss hanging out with friends      1
Family                                                                                                                                                                                                                        1
Badminton in court                                                                                                                                                                                                            1
Friends, relatives & travelling                                                                                                                                                                                               1
everything                                                                                                                                                                                                                    1
Friends and roaming around freely                                                                                                                                                                                             1
Metro                                                                                                                                                                                                                         1
School and friends.                                                                                                                                                                                                           1
My normal routine                                                                                                                                                                                                             1
All above                                                                                                                                                                                                                     1
Normal life                                                                                                                                                                                                                   1
Football                                                                                                                                                                                                                      1
Job                                                                                                                                                                                                                           1
Nothing this is my usual life                                                                                                                                                                                                 1
All of them                                                                                                                                                                                                                   1
Friends and School                                                                                                                                                                                                            1
Friends,Romaing and traveling                                                                                                                                                                                                 1
Taking kids to park                                                                                                                                                                                                           1
All of the above                                                                                                                                                                                                              1
All the above                                                                                                                                                                                                                 1
Internet                                                                                                                                                                                                                      1
Going to the movies                                                                                                                                                                                                           1
school, relatives and friends                                                                                                                                                                                                 1
All                                                                                                                                                                                                                           1
all of the above                                                                                                                                                                                                              1
Nothing                                                                                                                                                                                                                       1
Eating outside and friends.                                                                                                                                                                                                   1
Nah, this is my usual lifestyle anyway, just being lazy....                                                                                                                                                                   1
Family                                                                                                                                                                                                                        1
School and my school friends                                                                                                                                                                                                  1
Name: count, dtype: int64

In [68]:
df['What you miss the most'].replace(to_replace=['nothing','Nothing this is my usual life','I have missed nothing',
                                                'Nah, this is my usual lifestyle anyway, just being lazy.... ','NOTHING','.'] , value='Nothing', inplace=True)
df['What you miss the most'].replace(to_replace=['all','ALL','All the above','All of them','All of the above'] , value='All', inplace=True)
df['What you miss the most'].replace(to_replace=['Only friends','Travelling & Friends','Friends, relatives & travelling',
                                                'Friends,Romaing and traveling','school, relatives and friends','School and my school friends',
                                                ] , value='Friends , relatives', inplace=True)
df['What you miss the most'].replace(to_replace=['Badminton in court'],value='Playing',inplace=True)
df['What you miss the most'].replace(to_replace=['The idea of being around fun loving people but this time has certainly made us all to reconnect (and fill the gap if any) with our families and relatives so it is fun but certainly we do miss hanging out with friends      1 Family',
            'Going to the movies','Taking kids to park','Being social', 'Eating outside'],value='Going Outside',
                                     inplace=True)

In [69]:
df['What you miss the most'].value_counts()

What you miss the most
School/college                                                                                                                                                                                                              379
Friends , relatives                                                                                                                                                                                                         230
Travelling                                                                                                                                                                                                                  183
Roaming around freely                                                                                                                                                                                                       149
Going Outside                                                                                                                                                                                                               106
Colleagues                                                                                                                                                                                                                   67
All                                                                                                                                                                                                                          21
Nothing                                                                                                                                                                                                                      17
Gym                                                                                                                                                                                                                           4
Playing                                                                                                                                                                                                                       2
I have missed nothing                                                                                                                                                                                                         1
My normal routine                                                                                                                                                                                                             1
Being social                                                                                                                                                                                                                  1
Previous mistakes                                                                                                                                                                                                             1
Friends and roaming around freely                                                                                                                                                                                             1
To stay alone.                                                                                                                                                                                                                1
Family                                                                                                                                                                                                                        1
everything                                                                                                                                                                                                                    1
Normal life                                                                                                                                                                                                                   1
Metro                                                                                                                                                                                                                         1
The idea of being around fun loving people but this time has certainly made us all to reconnect (and fill the gap if any) with our families and relatives so it is fun but certainly we do miss hanging out with friends      1
All above                                                                                                                                                                                                                     1
Football                                                                                                                                                                                                                      1
Family                                                                                                                                                                                                                        1
Nah, this is my usual lifestyle anyway, just being lazy....                                                                                                                                                                   1
Eating outside and friends.                                                                                                                                                                                                   1
Nothing                                                                                                                                                                                                                       1
all of the above                                                                                                                                                                                                              1
All                                                                                                                                                                                                                           1
Internet                                                                                                                                                                                                                      1
All of the above                                                                                                                                                                                                              1
Friends and School                                                                                                                                                                                                            1
Job                                                                                                                                                                                                                           1
School and friends.                                                                                                                                                                                                           1
Name: count, dtype: int64

In [70]:
miss=pd.DataFrame(df['What you miss the most'].value_counts())

In [71]:
miss

                                                    count
What you miss the most
School/college                                        379
Friends , relatives                                   230
Travelling                                            183
Roaming around freely                                 149
Going Outside                                         106
Colleagues                                             67
All                                                    21
Nothing                                                17
Gym                                                     4
Playing                                                 2
I have missed nothing                                   1
My normal routine                                       1
Being social                                            1
Previous mistakes                                       1
Friends and roaming around freely                       1
To stay alone.                                          1
Family                                                  1
everything                                              1
Normal life                                             1
Metro                                                   1
The idea of being around fun loving people but ...      1
All above                                               1
Football                                                1
Family                                                  1
Nah, this is my usual lifestyle anyway, just be...      1
Eating outside and friends.                             1
Nothing                                                 1
all of the above                                        1
All                                                     1
Internet                                                1
All of the above                                        1
Friends and School                                      1
Job                                                     1
School and friends.                                     1

In [63]:
miss.shape

(36, 1)

In [72]:
df.to_csv("preCovidStudentSurvey.csv",index=0)

# Now the dataset is preprocessed and  ready for  Analysis Phase